name: Test PowerShell Script

on:
   push:
     branches: [ main ] 

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    -name: Run Powershell script
     shell: pwsh
     run: | 
        Write-Host "Running PowerShell script ..."
        .\Scripts\Envbootstrap.ps1
